musicbox/urls.py
from django.conf.urls import url

from . import views

app_name = 'musicbox'
urlpatterns = [
    # index
    url(r'^$', views.index, name='index'),
    # playlist, ex: /musicbox/5/
    url(r'^(?P<playlist_id>[0-9]+)/$', views.playlist, name='playlist'),
    # songinfo, ex: /musicbox/5/songinfo/
    url(r'^(?P<pk>[0-9]+)/songinfo/$', views.SonginfoView.as_view(), name='songinfo'),
    # play song in list
    url(r'^(?P<playlist_id>[0-9]+)/play/$', views.play, name='play'),
    # search song via netease music
    url(r'^search/$', views.search, name='search'),
    url(r'^addsongs/$', views.addsongs, name='addsongs'),
    # controls
    url(r'^play/$', views.play, name='play'),
    url(r'^stop/$', views.stop, name='stop'),
    url(r'^deleteSong/$', views.deleteSong, name='deleteSong'),
    # playlists
    url(r'^addplaylist/$', views.addplaylist, name='addplaylist'),
    url(r'^searchPlaylist/$', views.searchPlaylist, name='searchPlaylist'),
    url(r'^playlist/$', views.changePlaylist, name='changePlaylist'),
]

mynetease/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^musicbox/', include('musicbox.urls')),
    url(r'^admin/', admin.site.urls),
]

musicbox/models.py
from django.db import models
from django.utils.encoding import python_2_unicode_compatible

import datetime
from django.utils import timezone

# Create your models here.
@python_2_unicode_compatible  # only if you need to support Python 2
class Playlist(models.Model):
    # playlist_id = models.IntegerField()
    label = models.CharField(max_length=200)
    comment = models.CharField(max_length=200)
    create_date = models.DateTimeField('date created')
    def __str__(self):
        return self.label
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=10) <= self.create_date <= now

@python_2_unicode_compatible  # only if you need to support Python 2
class Song(models.Model):
    playlist = models.ForeignKey(Playlist, on_delete=models.CASCADE)
    song_name = models.CharField(max_length=200)
    artist_name = models.CharField(max_length=200)
    album_name = models.CharField(max_length=200)
    mp3_url = models.CharField(max_length=200)
    netease_id = models.IntegerField()
    def __str__(self):
        return self.song_name


# drop table if exists playlist;
# create table playlist (
#   playlist_id integer primary key autoincrement,
#   label text not null,
#   comment text
# );
#
# drop table if exists song;
# create table song (
#   song_id integer primary key autoincrement,
#   in_playlist integer not null,
#   netease_id integer not null,
#   song_name text not null,
#   artist_name text not null,
#   album_name text not null,
#   mp3_url text not null
# );

musicbox/views.py
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic
from django.template.loader import render_to_string

# cache to store simple variables
from django.core.cache import cache
from django.utils import timezone
from .models import Playlist, Song
import json

# netease api
import ast
import musicbox.api
import musicbox.player
netease = musicbox.api.NetEase()
musicPlayer = musicbox.player.Player()

# new api from https://github.com/Mellcap/MellPlayer
import musicbox.newApi
api_new = musicbox.newApi.Netease()

def changeUrlInPlaylist(playlist):
    # get song id in a playlist
    ids = []
    for song in playlist.song_set.all():
        ids.append(song.netease_id)
    # get new urls
    data = api_new.song_detail_new(ids)
    song_details = api_new.parse_info(data=data, parse_type='song_detail_new')
    # change url in list
    for song in playlist.song_set.all():
        mp3Url = song_details.get(song.netease_id, None)['song_url']
        if mp3Url != None and song.mp3_url != mp3Url:
            song.mp3_url = mp3Url
            song.save()
    return playlist

# def initPlaylistId():
#     pid = Playlist.objects.order_by('-create_date')[0].id
#     cache.set('playlist_now', pid, None)
#     cache.set('playlists', Playlist.objects.order_by('-create_date'), None)

# class IndexView(generic.ListView):
#     initPlaylistId();
#     template_name = 'musicbox/index.html'
#     context_object_name = 'latest_playlist'
#     def get_queryset(self):
#         """Return the last five created playlists."""
#         return Playlist.objects.order_by('-create_date')
def index(request):
    pid = Playlist.objects.order_by('-create_date')[0].id
    cache.set('playlist_now', pid, None)
    cache.set('playlists', Playlist.objects.order_by('-create_date'), None)
    context = {
        'playlist': changeUrlInPlaylist(get_object_or_404(Playlist, pk=cache.get('playlist_now'))),
        'playlists': cache.get('playlists')
    }
    return render(request, 'musicbox/playlist.html', context)

class SonginfoView(generic.DetailView):
    model = Song
    template_name = 'musicbox/songinfo.html'

# def index(request):
#     latest_playlist = Playlist.objects.order_by('-create_date')[:5]
#     context = {
#         'latest_playlist': latest_playlist,
#     }
#     return render(request, 'musicbox/index.html', context)
#
# def playlist(request, playlist_id):
#     playlist = get_object_or_404(Playlist, pk=playlist_id)
#     return render(request, 'musicbox/playlist.html', {'playlist': playlist})
#
#
# def songinfo(request, song_id):
#     song = get_object_or_404(Song, pk=song_id)
#     # response = "You're looking at the information of song %s."
#     return render(request, 'musicbox/songinfo.html', {'song':song})

def playlist(request, playlist_id):
    playlist = get_object_or_404(Playlist, pk=playlist_id)
    cache.set('playlist_now', playlist_id, None)
    playlists = cache.get('playlists')
    playlist = changeUrlInPlaylist(playlist)
    return render(request, 'musicbox/playlist.html', {'playlist': playlist, 'playlists': playlists})

################################################################################
def play(request):
    playlist = get_object_or_404(Playlist, pk=cache.get('playlist_now'))
    if request.GET['song_id'] != '0':
        try:
            selected_song = playlist.song_set.get(pk=request.GET['song_id'])
        except (KeyError, Song.DoesNotExist):
            # Redisplay the question voting form.
            return render(request, 'musicbox/playlist.html', {
                'playlist': playlist,
                'error_message': "You didn't select a song.",
            })
        else:
            # print selected_song
            url_list = []
            url_list.append(selected_song.mp3_url)
            # append other songs in list
            other_song = playlist.song_set.all().exclude(pk=request.GET['song_id'])
            for song in other_song[::-1]:
                url_list.append(song.mp3_url)
            # play with system player
            musicPlayer.playUrl(url_list)
            return render(request, 'musicbox/playlist.html', {
                'playlist': playlist,
                'playlists': cache.get('playlists'),
            })         # return HttpResponseRedirect(reverse('musicbox:playlist', args=(selected_song.id,)))
    else: # not specify starting song
        url_list = []
        other_song = playlist.song_set.all()
        for song in other_song[::-1]:
            url_list.append(song.mp3_url)
        # play with system player
        musicPlayer.playUrl(url_list)
        return render(request, 'musicbox/playlist.html', {
            'playlist': playlist,
            'playlists': cache.get('playlists'),
        })



def stop(request):
    playlist = get_object_or_404(Playlist, pk=cache.get('playlist_now'))
    musicPlayer.stop()
    return render(request, 'musicbox/playlist.html', {
        'playlist': playlist,
        'playlists': cache.get('playlists'),
    })

################################################################################
# get song information from netease api
def getSongInfo(searchStr):
    data = netease.search(searchStr)
    song_ids = []
    if 'songs' in data['result']:
        if 'mp3Url' in data['result']['songs']:
            songs = data['result']['songs']
        # if search song result do not has mp3Url
        # send ids to get mp3Url
        else:
            for i in range(0, len(data['result']['songs'])):
                song_ids.append(data['result']['songs'][i]['id'])
            songs = netease.songs_detail(song_ids)
        songinfo =  netease.dig_info(songs, 'songs')
    else:
        songinfo = []
    return songinfo

def search(request):
    playlist = get_object_or_404(Playlist, pk=cache.get('playlist_now'))
    try:
        songinfo = getSongInfo(request.POST['searchStr'])
    except:
        response = dict(error='error')
    else:
        response = dict(error='no')
        search_result = []
        for i in range(0, len(songinfo)):
            if songinfo[i]['mp3_url']:
                temp = dict(netease_id=songinfo[i]['song_id'], song_name=songinfo[i]['song_name'], artist_name=songinfo[i]['artist'],
                            album_name=songinfo[i]['album_name'], mp3_url=songinfo[i]['mp3_url'])
                search_result.append(temp)
        response['search_results'] = render_to_string('musicbox/ajaxSong.html', {'search_result': search_result})
        return HttpResponse(json.dumps(response))

def addsongs(request):
    playlist = get_object_or_404(Playlist, pk=cache.get('playlist_now'))
    for name in request.POST:
        song = request.POST[name]
        if 'song_name' in song:
            # convert to dictionary
            song = ast.literal_eval(song)
            # print song['song_name']
            playlist.song_set.create(song_name = song['song_name'],
                                     artist_name = song['artist_name'],
                                     album_name = song['album_name'],
                                     mp3_url = song['mp3_url'],
                                     netease_id = song['netease_id'])
    # generate mp3_urls for front-end
    songInfo = []
    playlist = changeUrlInPlaylist(playlist)
    for song in playlist.song_set.all():
        dict_temp = {"title" : song.song_name, "artist" : song.artist_name, "source" : song.mp3_url, "songid" : song.id, "status" : "live"}
        songInfo.append(dict_temp)
    songInfo.reverse()
    # multiple html parts
    response = dict(songlist=render_to_string('musicbox/ajaxSong.html', {'playlist':playlist}))
    response['urllist'] = json.dumps(songInfo)
    return HttpResponse(json.dumps(response))

def deleteSong(request):
    response = dict(song_id=request.GET['song_id'])
    response['error'] = True
    playlist = get_object_or_404(Playlist, pk=cache.get('playlist_now'))
    if request.GET['song_id'] != '0':
        try:
            selected_song = playlist.song_set.get(pk=request.GET['song_id'])
        except (KeyError, Song.DoesNotExist):
            # Redisplay the question voting form.
            return HttpResponse(json.dumps(response))
        else:
            # print selected_song
            selected_song.delete()
            response['error'] = False
            return HttpResponse(json.dumps(response))
    else: # not specify delete song
        return HttpResponse(json.dumps(response))

################################################################################
# add or search for existing playlists
def addplaylist(request):
    newlist = Playlist(label=request.POST['playlist_label'], comment=request.POST['playlist_comment'], create_date=timezone.now())
    newlist.save()
    # create empty playlist
    if request.POST['playlist_type'] == 'new':
        pass
    # add songs in user playlist to new list
    elif request.POST['playlist_type'] == 'user':
        data = netease.playlist_detail(request.POST['playlist_searchReId'])
        songs = netease.dig_info(data, 'songs')
        songs.reverse()
        for song in songs:
            newlist.song_set.create(song_name = song['song_name'],
                                     artist_name = song['artist'],
                                     album_name = song['album_name'],
                                     mp3_url = song['mp3_url'],
                                     netease_id = song['song_id'])
    # added and jump to playlist view
    cache.set('playlist_now', newlist.id, None)
    cache.set('playlists', Playlist.objects.order_by('-create_date'), None)
    return render(request, 'musicbox/playlist.html', {
        'playlist': newlist,
        'playlists': cache.get('playlists'),
    })

def getListInfo(searchStr):
    data = netease.search(searchStr, stype=1000)

musicbox/templates/musicbox/ajaxPlaylist.html
{% if playlists %}
    <ul class="nav nav-sidebar" id="sideNavPlaylist">
    {% for plist in playlists %}
      {% if plist.id == playlist.id  %}
      <li><a href="#" data-playlistid="{{ plist.id }}" class="active">{{ plist.label }}</a></li>
    {% else %}
      <li><a href="#" data-playlistid="{{ plist.id }}" >{{ plist.label }}</a></li>
      {% endif %}
    {% endfor %}
    </ul>
{% else %}
    <p>No Playlists are available.</p>
{% endif %}

musicbox/templates/musicbox/ajaxSong.html
{% if playlist %}
  <!-- <div class="table-responsive">
    <table class="table table-hover" id="songlist"> -->
      <thead>
        <tr class="clickable-row">
          <th id="play_action" class="hidden-xs-down">#</th>
          <th id="Title"> Title </th>
          <th id="Artist"> Artist </th>
          <th id="Album" class="hidden-xs-down"> Album </th>
          <th id="Link" class="hidden-sm-down"> Link </th>
        </tr>
      </thead>
      <tbody>
        {% for song in playlist.song_set.all reversed %}
        <tr class="clickable-row">
          <td data-songid="{{song.id}}" class="hidden-xs-down">{{forloop.counter}}</td>
          <td>{{song.song_name}}</td>
          <td>{{song.artist_name}}</td>
          <td class="hidden-xs-down">{{song.album_name}}</td>
          <td class="hidden-sm-down"><a href="http://music.163.com/#/song?id={{ song.netease_id}}" target="_blank">Netease</a></td>
        </tr>
        {% endfor %}
      </tbody>
    <!-- </table>
  </div> -->
{% endif %}

{% if search_result %}
<!-- <form action="{% url 'musicbox:addsongs' %}" method="post">
  {% csrf_token %}
  <button type="submit" class="btn btn-danger">Add</button>
  <div class="table-responsive">
    <table class="table table-hover" id="searchSonglist"> -->
      <thead>
        <tr class="clickable-row">
          <th id="play_action" class="hidden-xs-down">#</th>
          <th id="Title"> Title </th>
          <th id="Artist"> Artist </th>
          <th id="Album"> Album </th>
          <th id="Link" class="hidden-sm-down"> Link </th>
        </tr>
      </thead>
      <tbody>
          {% for song in search_result %}
          <tr class="clickable-row">
            <td class="hidden-xs-down">
              <input type="checkbox" class="hidden-xs-up" name="song{{ forloop.counter }}_to_add" id="song{{ forloop.counter }}" value="{{ song }}" />
              <label for="song{{ forloop.counter }}">{{ forloop.counter }}</label><br />
            </td>
            <td>{{song.song_name}}</td>
            <td>{{song.artist_name}}</td>
            <td>{{song.album_name}}</td>
            <td class="hidden-sm-down"><a href="http://music.163.com/#/song?id={{ song.netease_id}}" target="_blank">Netease</a></td>
          </tr>
          {% endfor %}
      </tbody>
    <!-- </table>
  </div>
</form> -->
{% endif %}

musicbox/templates/musicbox/ajaxTitle.html
{% if playlist %}
<h4 class="hidden-xs-down"><stong data-toggle="tooltip" data-placement="bottom" title="{{ playlist.comment }}">{{ playlist.label }} </strong></h4>
<p class="text-xs-right hidden-xs-down">{{ playlist.create_date }} </p>
{% endif %}

musicbox/templates/musicbox/playlist.html
{% extends "musicbox/base.html" %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<!-- <form action="{% url 'musicbox:play' playlist.id %}" method="post">
{% csrf_token %}
{% for song in playlist.song_set.all %}
<input type="radio" name="song" id="song{{ forloop.counter }}" value="{{ song.id }}" />
<label for="song{{ forloop.counter }}">{{ song.song_name }}</label><br />
{% endfor %}
<input type="submit" value="play" />
</form> -->


{% block title %}Netease Music Simple{% endblock %}

{% block sidebar %}
{% if playlists %}
<ul class="nav nav-sidebar" id="sideNavPlaylist">
  {% for plist in playlists %}
  {% if plist.id == playlist.id  %}
  <li><a href="#" data-playlistid="{{ plist.id }}" class="active">{{ plist.label }}</a></li>
  {% else %}
  <li><a href="#" data-playlistid="{{ plist.id }}" >{{ plist.label }}</a></li>
  {% endif %}
  {% endfor %}
</ul>
{% else %}
<p>No Playlists are available.</p>
{% endif %}
{% endblock %}

<!-- start playlist details -->
{% block listname %}
<div id="titleblock">
  <h4 class="hidden-xs-down"><stong data-toggle="tooltip" data-placement="bottom" title="{{ playlist.comment }}">{{ playlist.label }} </strong></h4>
    <p class="text-xs-right hidden-xs-down">{{ playlist.create_date }} </p>
  </div>
  {% endblock %}

  {% block mainlist %}
  <div class="table-responsive">
    <table class="table table-hover" id="songlist">
      <thead>
        <tr class="clickable-row">
          <th id="play_action" class="hidden-xs-down">#</th>
          <th id="Title"> Title </th>
          <th id="Artist"> Artist </th>
          <th id="Album" class="hidden-xs-down"> Album </th>
          <th id="Link" class="hidden-sm-down"> Link </th>
        </tr>
      </thead>
      <tbody>
        {% for song in playlist.song_set.all reversed %}
        <tr class="clickable-row">
          <td data-songid="{{song.id}}" class="hidden-xs-down">{{forloop.counter}}</td>
          <td>{{song.song_name}}</td>
          <td>{{song.artist_name}}</td>
          <td class="hidden-xs-down">{{song.album_name}}</td>
          <td class="hidden-sm-down"><a href="http://music.163.com/#/song?id={{ song.netease_id}}" target="_blank">Netease</a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <div class="audio" hidden="hidden">
      <audio id="hidden-song" src="" type="audio/mpeg"></audio>
  </div>
  {% endblock %}


  {% block modal %}
  <div class="modal fade" id="playlistModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title" id="myModalLabel">Add new playlist</h4>
        </div>
        <div class="modal-body">
          <form method="post" action="{% url 'musicbox:addplaylist' %}" id="playlist-form">
            {% csrf_token %}
            <div class="form-group">
              <label for="playlist-name" class="form-control-label">Label / Search terms:</label>
              <input type="text" class="form-control" id="playlist-name" name="playlist_label" required>
            </div>
            <div class="form-group">
              <label for="comment-text" class="form-control-label">Comment:</label>
              <textarea class="form-control" id="comment-text" name="playlist_comment" required></textarea>
            </div>
            <div class="form-group hidden-xs-up">
              <input type="text" class="form-control" id="playlist-type" name="playlist_type" value="new">
            </div>
            <div class="form-group hidden-xs-up">
              <input type="text" class="form-control" id="playlist-searchReId" name="playlist_searchReId" value="">
            </div>
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-success" id="search-playlist">Search</button>
          <button type="button" class="btn btn-primary" id="submit-playlist">Add</button>
        </div>
        <!-- search playlists results part -->
        <div class="modal-extrainfo"></div>
      </div>
    </div>
  </div>

  <div class="modal fade" id="songModal" tabindex="-1" role="dialog" aria-labelledby="mySongModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title" id="mySongModalLabel">Search Results</h4>
        </div>
        <div class="modal-body">
          <form id="addsongForm" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Add</button>
            <div class="table-responsive">
              <table class="table table-hover" id="searchSonglist">
              </table>
            </div>
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
  {% endblock %}

  {% block extratail %}
  <script>
  $(function () {
    $('[data-toggle="tooltip"]').tooltip();
  })

  // audio element
  var audio = $("audio#hidden-song")[0];
  var firstLog = true;
  var shuffle = false;
  var playing = false;

  // music list:
  var SongInfo = [
    {% for song in playlist.song_set.all reversed %}
    {
      "title" : "{{song.song_name}}",
      "artist" : "{{song.artist_name}}",
      "source" : "{{song.mp3_url}}",
      "songid" : "{{song.id}}",
      "status" : "live"
    },
    {% endfor %}
  ];
  var SongInfo_new = undefined;

  // generate playlist html
  var songTotal = SongInfo.length;

  // select song to play first
  var song_play = 0;
  // audio.src = SongInfo[song_play].source;

  $('#songlist').on('click', '.clickable-row', function(event) {
    // change list if not current playlist
    firstLog = false;
    changeList();
    // find clicked song
    $(this).addClass('selected-song').siblings().removeClass('selected-song');
    song_play = Number($(this).find('td:first').html()) - 1;
    // song_selected = $(this).find('td:first').data('songid');
    // click to play
    audio.src = SongInfo[song_play].source;
    audioPlay();
  });

  $('#play_btn').click(function() {
    if (playing){
      audio.pause();
      playing = false;
      $(this).find($(".fa")).removeClass('fa-pause').addClass('fa-play');
      $("#playIndicator").html("<p>Paused: "+SongInfo[song_play].title+" - "+SongInfo[song_play].artist+"</p>");
    }else{
      if (firstLog){
        audio.src = SongInfo[song_play].source;
        firstLog = false;
      }
      audioPlay();
    }
  });

  $('#next_btn').click(function() {
    playNext();
  });

  $('#random_btn').click(function() {
    if (shuffle) {
      shuffle = false;
    }else{
      shuffle = true;
    }
  });

  // hide indicator when clicked
  $('#playIndicator').click(function() {
    $(this).hide();
  });

  // continue playing next song if current song is ended
  audio.addEventListener('ended',function(){
    if (! firstLog){
      playNext();
    }
  },false);

  // if song is unaccesiable
  audio.addEventListener('error',function(){
    if (! firstLog){
      $.ajax({
        url: '{% url 'musicbox:deleteSong' %}',
        method: 'GET', // or another (GET), whatever you need
        data: {
          song_id: SongInfo[song_play].songid, // data you need to pass to your function
        },
        success: function (response) {
          res = JSON.parse(response);  // Get the results sended from ajax to here
          if (res.error) { // If the function fails
            // Error
            console.log('Delete failed! ');
          } else {  // Success
            $('td[data-songid=' + res.song_id + ']').parent().hide();
            SongInfo[song_play].status = "dead";
            playNext();
          }
        }
      });
    }
  },false);

  function audioPlay(){
    audio.play();
    playing = true;
    $('#play_btn').find($(".fa")).removeClass('fa-play').addClass('fa-pause');
    // indicator
    $("#playIndicator").html("<p>Now Playing: "+SongInfo[song_play].title+" - "+SongInfo[song_play].artist+"</p>");
    $("#playIndicator").show();
  }

  function playNext(){
    if (!shuffle){
      while (true){
        song_play = song_play == songTotal-1 ? 0 : song_play+1;
        if (SongInfo[song_play].status === "live"){
          audio.src = SongInfo[song_play].source;
          break;
        }
      }
    }else{
      while (true){
        song_play = parseInt(Math.random() * songTotal);
        if (SongInfo[song_play].status === "live"){
          audio.src = SongInfo[song_play].source;
          break;
        }
      }
    }
    audioPlay();
  }

  function changeList(){
    if (SongInfo_new){
      SongInfo = SongInfo_new;
      song_play = 0;
      audio.src = SongInfo[song_play].source;
      songTotal = SongInfo.length;
    }
  }

  $('#delete_btn').click(function() {
    $.ajax({
      url: '{% url 'musicbox:deleteSong' %}',
      method: 'GET', // or another (GET), whatever you need
      data: {
        song_id: SongInfo[song_play].songid, // data you need to pass to your function
      },
      success: function (response) {
        res = JSON.parse(response);  // Get the results sended from ajax to here
        if (res.error) { // If the function fails
          // Error
          console.log('Delete failed! ');
        } else {  // Success
          $('td[data-songid=' + res.song_id + ']').parent().hide();
          SongInfo[song_play].status = "dead";
          playNext();
        }
      }
    });
  });

  // submit add playlist form or search for online playlists
  $('#submit-playlist').click(function(){
    $('#playlist-form').submit();
  });

  $('#search-playlist').click(function(){
    var searchStrList = $('#playlist-name').val();
    $.ajax({
      method: 'GET',
      url: '{% url 'musicbox:searchPlaylist' %}',
      data: {'searchStrList': searchStrList},
      success : function(data) {
        $('.modal-extrainfo').html(data);
        $('#searchReList').on('click', '.clickable-row', function(event) {
          console.log('click');
          $('#playlist-name').val($(this).find('td:nth-child(2)').html());
          $('#comment-text').val('From online user\'s playlist. Creator: ' + $(this).find('td:nth-child(3)').html());
          $('#playlist-type').val('user');
          $('#playlist-searchReId').val($(this).find('td:first').data('playlistid'));
        });
      }
    });
  });

  $('#playlistModal').on('hidden.bs.modal', function (e) {
    $('.modal-extrainfo').html('');
    $('#playlist-name').val('');
    $('#comment-text').val('');
    $('#playlist-type').val('new');
    $('#playlist-searchReId').val('');
  });

  $('body').on('click','#sideNavPlaylist a',function(){
    // console.log($(this).data('playlistid'));
    $.ajax({
      method: 'GET',
      url: '{% url 'musicbox:changePlaylist' %}',
      data: {'pid': $(this).data('playlistid')},
      success : function(response){
        res = JSON.parse(response);
        $('#titleblock').html(res.title);
        $('#sidenav').html(res.sidebar);
        $('#songlist').html(res.songlist);
        // slideout.toggle();
        if( $('.main').css('padding-right')!='40px') {
          slideout.toggle();
        }
        // songinfo change
        SongInfo_new = JSON.parse(res.urllist);
      }
    });
  });

  // search songs ajax post
  $('#searchForm').submit(function(e) {
    $.ajax({
      type: 'POST',
      url: '{% url 'musicbox:search' %}',
      data: $('#searchForm').serialize(), // serializes the form's elements.
      success: function(response){
        res = JSON.parse(response);
        if(res.error=='no'){
          $('#searchSonglist').html(res.search_results);
          $('#songModal').modal('show');
          // $('#searchSonglist').on('click', '.clickable-row', function(event) {
          //   var fCheck = $(this).find('input[type="checkbox"]');
          //   fCheck.prop('checked', !fCheck.prop('checked'));
          //   $(this).toggleClass('selected-song');
          // });
        }else {
          alert('Cannot find search results!');
        }
      }
    });
    e.preventDefault(); // avoid to execute the actual submit of the form.
  });

  $('#searchSonglist').on('click', '.clickable-row', function(event) {
    var fCheck = $(this).find('input[type="checkbox"]');
    fCheck.prop('checked', !fCheck.prop('checked'));
    $(this).toggleClass('selected-song');
  });

  $('#addsongForm').submit(function(e) {
    $.ajax({
      type: 'POST',
      url: '{% url 'musicbox:addsongs' %}',
      data: $('#addsongForm').serialize(), // serializes the form's elements.
      success: function(response){
        res = JSON.parse(response);
        $('#songModal').modal('hide');
        $('#songlist').html(res.songlist);
        // songinfo change
        SongInfo_new = JSON.parse(res.urllist);
      }
    });
    e.preventDefault(); // avoid to execute the actual submit of the form.
  });

  $('#songModal').on('hidden.bs.modal', function (e) {
    $('#searchForm').find('input[name="searchStr"]').val('');
    $('#searchSonglist').html('');
  });



  </script>

  {% endblock %}